WIP: [2FA] get rid of split-MFA

diff --git a/anti-evil-maid/sbin/anti-evil-maid-install b/anti-evil-maid/sbin/anti-evil-maid-install
--- a/anti-evil-maid/sbin/anti-evil-maid-install
+++ b/anti-evil-maid/sbin/anti-evil-maid-install
@@ -11,7 +11,7 @@ usage() {
     cat <<END
 
 Usage:
-  anti-evil-maid-install [-s <suffix>] [-F] [-m] [-M <device>] [-S <suffix>] <device>
+  anti-evil-maid-install [-s <suffix>] [-F] [-m] <device>
 
   Installs Anti Evil Maid to your system's boot partition, or to a different
   storage device (e.g. an SD card or a USB stick).
@@ -34,13 +34,6 @@ Arguments:
       Using time-based one time password and a LUKS key file, provides resistance
       to shoulder surfing and video surveillance based passphrase snooping.
 
-  -M: split multi-factor AEM (key file on separate media); implies "-m"
-      Slightly increases resistance to multi-stage evil maid attacks.
-
-  -S: label suffix for split multi-factor AEM device
-      Same semantics as the "-s" argument listed above, except the length
-      limit is 0-7 characters here.
-
 
 Examples:
   Install on the system's boot partition (assuming that it is /dev/sda1), and
@@ -53,14 +46,10 @@ Examples:
 
     anti-evil-maid-install -s .sd /dev/mmcblk0p1
 
-  Install 2FA-enabled AEM on USB stick's first partition, overwriting it with
+  Install MFA-enabled AEM on USB stick's first partition, overwriting it with
   a new ext4 filesystem and marking it bootable:
 
     anti-evil-maid-install -m /dev/sdb1
-
-  Same as above, but storing LUKS key file on a separate USB stick (/dev/sdc1):
-
-    anti-evil-maid-install -M /dev/sdc1 /dev/sdb1
 
 END
 
@@ -71,23 +60,18 @@ END
 # check invocation
 
 alias mfa=false
-unset LABEL_SUFFIX F SPLIT_DEV SPLIT_LABEL_SUFFIX
-while getopts s:FhmM:S: opt; do
+unset LABEL_SUFFIX F
+while getopts s:Fhm opt; do
     case "$opt" in
         s) LABEL_SUFFIX=$OPTARG ;;
         F) F=-F ;;
         m) alias mfa=true ;;
-        M) alias mfa=true; SPLIT_DEV=$OPTARG ;;
-        S) SPLIT_LABEL_SUFFIX=$OPTARG ;;
         *) usage ;;
     esac
 done
 
 case "$LABEL_SUFFIX" in *[!$LABEL_SUFFIX_CHARS]*|??????????????*) usage; esac
 LABEL=$LABEL_PREFIX$LABEL_SUFFIX
-
-case "$SPLIT_LABEL_SUFFIX" in *[!$LABEL_SUFFIX_CHARS]*|????????*) usage; esac
-SPLIT_LABEL=$SPLIT_LABEL_PREFIX$SPLIT_LABEL_SUFFIX
 
 shift $(($OPTIND - 1))
 case $# in
@@ -144,34 +128,6 @@ elif mfa && ! removable "$PART_DEV" "$LABEL" ; then
 fi
 
 
-# examine split-MFA device
-
-if [ -n "$SPLIT_DEV" ]; then
-    SPLIT_WHOLE_DEV=$(lsblk -dnp -o PKNAME "$SPLIT_DEV")
-    if ! [ -b "$SPLIT_WHOLE_DEV" -a "$SPLIT_WHOLE_DEV" != "$SPLIT_DEV" ]; then
-        log "Couldn't find parent device: $SPLIT_WHOLE_DEV"
-        exit 1
-    fi
-
-    SPLIT_PART_DEV_REAL=$(readlink -f "$SPLIT_DEV")
-    SPLIT_PART_NUM=${SPLIT_PART_DEV_REAL##*[!0-9]}
-    if ! [ "$SPLIT_PART_NUM" -gt 0 ]; then
-        log "Couldn't extract partition number: $SPLIT_PART_NUM"
-        exit 1
-    fi
-
-    if ! external "$SPLIT_DEV"; then
-        log "Split-MFA cannot be installed on the same storage device as Qubes OS."
-        exit 1
-    elif ! removable "$SPLIT_DEV" "$SPLIT_LABEL"; then
-        log "Split-MFA can only be used with removable media."
-        log "Should the device be, in fact, removable (autodetection failed),"
-        log "add '.rm=1' at the end of disk label suffix using the '-S' option."
-        exit 1
-    fi
-fi
-
-
 # This check (instead of a more obvious 'mountpoint $BOOT_DIR') should work
 # even in unusual setups without any internal boot partition at all:
 
@@ -193,19 +149,6 @@ case "$OLD_LABEL" in "$LABEL_PREFIX"*)
 esac
 
 
-# split-MFA label keeper
-if [ -n "$SPLIT_DEV" ]; then
-    OLD_SPLIT_LABEL=$(lsblk -dnr -o LABEL "$SPLIT_DEV") ||
-    OLD_SPLIT_LABEL=
-
-    case "$OLD_SPLIT_LABEL" in "$SPLIT_LABEL_PREFIX"*)
-        if [ -z "${SPLIT_LABEL_SUFFIX+set}" ]; then
-            SPLIT_LABEL=$OLD_SPLIT_LABEL
-        fi
-    esac
-fi
-
-
 # create and/or label fs
 
 if replace; then
@@ -214,14 +157,6 @@ if replace; then
 else
     log "Labeling filesystem $LABEL"
     e2label "$PART_DEV" "$LABEL"
-fi
-
-
-# always recreate split-MFA FS
-
-if [ -n "$SPLIT_DEV" ]; then
-    log "Creating new ext4 filesystem labeled $SPLIT_LABEL"
-    mkfs.ext4 $F -L "$SPLIT_LABEL" "$SPLIT_DEV"
 fi
 
 
@@ -310,53 +245,45 @@ if mfa && [ ! -e "$AEM_DIR/$LABEL/secret.otp" ]; then
     log "TOTP code matches, continuing AEM setup."
 fi
 
+
 # MFA: generate and enroll a LUKS key file if not already present
 
-if mfa; then
-    if [ -n "$SPLIT_DEV" ]; then
-        KEY_PATH="$AEM_DIR/$SPLIT_LABEL/secret.key"
-        echo "$SPLIT_LABEL" > "$AEM_DIR/$LABEL/split-mfa.label"
-    else
-        KEY_PATH="$AEM_DIR/$LABEL/secret.key"
-    fi
+if mfa && [ ! -e "$AEM_DIR/$LABEL/secret.key" ]; then
+    log "Generating new LUKS key file"
+    rawkey=$(mktemp)
+    head -c 64 /dev/random > "$rawkey"
 
-    if [ ! -e "$KEY_PATH" ]; then
-        log "Generating new LUKS key file"
-        rawkey=$(mktemp)
-        head -c 64 /dev/random > "$rawkey"
+    log "Encrypting key file"
+    mkdir -p "$AEM_DIR/$LABEL"
+    scrypt enc "$rawkey" "$AEM_DIR/$LABEL/secret.key"
 
-        log "Encrypting key file"
-        mkdir -p "$(dirname "$KEY_PATH")"
-        scrypt enc "$rawkey" "$KEY_PATH"
+    for dev in $(getluksuuids); do
+        devname=$(readlink -f "/dev/disk/by-uuid/$dev")
 
-        for dev in $(getluksuuids); do
-            devname=$(readlink -f "/dev/disk/by-uuid/$dev")
+        # check if LUKS device has any free key slots
+        # FIXME: possibility of failing due to i18n?
+        if ! cryptsetup luksDump "/dev/disk/by-uuid/$dev" \
+                | grep -q DISABLED; then
+            log "FATAL: Device $devname (UUID $dev) has no free key slots!"
+            exit 1
+        fi
 
-            # check if LUKS device has any free key slots
-            # FIXME: possibility of failing due to i18n?
-            if ! cryptsetup luksDump "/dev/disk/by-uuid/$dev" \
-                    | grep -q DISABLED; then
-                log "FATAL: Device $devname (UUID $dev) has no free key slots!"
+        log "Adding key file to new key slot for $devname (UUID $dev)"
+        for try in 1 2 3; do
+            if cryptsetup luksAddKey "/dev/disk/by-uuid/$dev" "$rawkey"; then
+                break
+            elif [ $try -eq 3 ]; then
+                log "ERROR: Wrong password, aborting!"
+                log "You need to manually finish enrolling $rawkey"
+                log "as a key file for all desired LUKS devices, then"
+                log "remove the $rawkey file and re-run this script."
                 exit 1
             fi
-
-            log "Adding key file to new key slot for $devname (UUID $dev)"
-            for try in 1 2 3; do
-                if cryptsetup luksAddKey "/dev/disk/by-uuid/$dev" "$rawkey"; then
-                    break
-                elif [ $try -eq 3 ]; then
-                    log "ERROR: Wrong password, aborting!"
-                    log "You need to manually finish enrolling $rawkey"
-                    log "as a key file for all desired LUKS devices, then"
-                    log "remove the $rawkey file and re-run this script."
-                    exit 1
-                fi
-            done
         done
+    done
 
-        log "Shredding the unencrypted key file"
-        shred -zu "$rawkey"
-    fi
+    log "Shredding the unencrypted key file"
+    shred -zu "$rawkey"
 fi
 
 
@@ -374,33 +301,11 @@ else
 fi
 
 
-# mount split-MFA (cannot be already mounted since we always reformat)
-if mfa && [ -n "$SPLIT_DEV" ]; then
-    SPLIT_MNT=/mnt/anti-evil-maid/$SPLIT_LABEL
-    log "Mounting split-MFA at $SPLIT_MNT"
-    mkdir -p "$SPLIT_MNT"
-    mount "$SPLIT_DEV" "$SPLIT_MNT"
-fi
-
-
 # sync
 
 mkdir -p "$PART_MNT/aem"
 synctpms "$LABEL" "$PART_MNT"
 mkdir -p "$AEM_DIR/$LABEL"
-
-if mfa && [ -n "$SPLIT_DEV" ]; then
-    # store split-MFA label on first AEM dev
-    cp "$AEM_DIR/$LABEL/split-mfa.label" "$PART_MNT/aem/"
-fi
-
-# sync split-MFA
-
-if mfa && [ -n "$SPLIT_DEV" ]; then
-    mkdir -p "$SPLIT_MNT/aem"
-    synctpms "$SPLIT_LABEL" "$SPLIT_MNT"
-    # mkdir -p "$AEM_DIR/$SPLIT_LABEL" not needed here
-fi
 
 
 # make device bootable
@@ -445,9 +350,4 @@ fi
 if [ -z "$CUR_MNT" ]; then
     log "Unmounting $PART_MNT"
     umount "$PART_MNT"
-fi
-
-if mfa && [ -n "$SPLIT_DEV" ]; then
-    log "Unmounting $SPLIT_DEV"
-    umount "$SPLIT_DEV"
 fi
